# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boisson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('points', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('points', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('points', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fromage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('points', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LieuRestauration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('tempsAttente', models.IntegerField(null=True)),
                ('note', models.FloatField(null=True)),
                ('distance', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('pain', models.NullBooleanField()),
                ('boisson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipale.Boisson')),
                ('dessert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipale.Dessert')),
                ('entree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipale.Entree')),
                ('fromage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipale.Fromage')),
                ('lieuRestauration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipale.LieuRestauration')),
            ],
        ),
        migrations.CreateModel(
            name='PlatPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('points', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='platPrincipal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipale.PlatPrincipal'),
        ),
        migrations.AddField(
            model_name='lieurestauration',
            name='boisson',
            field=models.ManyToManyField(through='appPrincipale.Menu', to='appPrincipale.Boisson'),
        ),
        migrations.AddField(
            model_name='lieurestauration',
            name='dessert',
            field=models.ManyToManyField(through='appPrincipale.Menu', to='appPrincipale.Dessert'),
        ),
        migrations.AddField(
            model_name='lieurestauration',
            name='entree',
            field=models.ManyToManyField(through='appPrincipale.Menu', to='appPrincipale.Entree'),
        ),
        migrations.AddField(
            model_name='lieurestauration',
            name='fromage',
            field=models.ManyToManyField(through='appPrincipale.Menu', to='appPrincipale.Fromage'),
        ),
        migrations.AddField(
            model_name='lieurestauration',
            name='platPrincipal',
            field=models.ManyToManyField(through='appPrincipale.Menu', to='appPrincipale.PlatPrincipal'),
        ),
    ]
