# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0004_lieurestauration_typer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieurestauration',
            name='codePostal',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
