# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0005_lieurestauration_codepostal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.ManyToManyField(to='appPrincipale.LieuRestauration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appPrincipale.UserProfile')),
            ],
        ),
    ]
