# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0009_auto_20171224_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
