# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0013_auto_20180127_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieurestauration',
            name='posX',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='lieurestauration',
            name='posY',
            field=models.FloatField(null=True),
        ),
    ]
