# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0014_auto_20180128_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='allergie',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='regime',
        ),
        migrations.AddField(
            model_name='platprincipal',
            name='allergie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipale.Allergie'),
        ),
        migrations.AddField(
            model_name='platprincipal',
            name='regime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipale.Regime'),
        ),
    ]
