# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPrincipale', '0015_auto_20180130_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pain',
        ),
        migrations.AddField(
            model_name='reservation',
            name='lieu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appPrincipale.LieuRestauration'),
        ),
    ]
